name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17' # O la versión que estés utilizando
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_FLOWER_061918710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Usado para integraciones de Github (por ejemplo, comentarios en PR)
          action: "upload"
          ###### Configuraciones del Repositorio/Build - Estos valores se pueden configurar para coincidir con los requisitos de tu aplicación. ######
          # Para obtener más información sobre las configuraciones del flujo de trabajo de Static Web App, visita: https://aka.ms/swaworkflowconfig
          app_location: "/" # Ruta del código fuente de la aplicación
          api_location: "" # Ruta del código fuente de la API - opcional
          output_location: "build" # Directorio del contenido de la aplicación construida - opcional
          ###### Fin de Configuraciones del Repositorio/Build ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_FLOWER_061918710 }}
          action: "close"
